### ISSUE TITLE
update traineddata

### ISSUE THREAD

**Issue by softboy99** [tesseract-ocr/tessdata#140]
traineddata hasn't been updated for 2 years. Is there newer traineddata after 4.1.1 released？

**Comment by stweil** [comment]
You are right, the model files don't get many updates because nobody trains newer better models to replace the existing ones. But of course there also exist other models for Tesseract which were trained later, for example my own [training results](https://ub-backup.bib.uni-mannheim.de/~stweil/tesstrain/).

Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
